default:
  image: node:18.14.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=A6Moi2cDLGk337rJpG1vZO0d
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=A6Moi2cDLGk337rJpG1vZO0d

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=A6Moi2cDLGk337rJpG1vZO0d
    - vercel build --prod --token=A6Moi2cDLGk337rJpG1vZO0d
    - vercel deploy --prebuilt --prod --token=A6Moi2cDLGk337rJpG1vZO0d